# سؤالِ دوم


توی این تمرین یه مقدار بیشتر با خواص تریس ماتریس‌ها آشنا می‌شویم. توجه کنید که تریس یک ماتریس $d\times d$ برابر با مجموع عناصر روی قطر آن است. طبق نمادگذاری دیراک 
تعریف تریس به فرم زیر است:
 $$\mathrm{tr} A=\sum_{i=0}^{d-1} \langle i\vert A\vert i\rangle$$
 
1. نشان دهید تعریف $\mathrm{tr}$ مستقل از انتخاب پایه است. یعنی برای هر پایه‌ی متعامد یکه‌ی ‌دیگری مانند
$\{\vert v_0 \rangle, \vert v_1 \rangle, \dots,\vert v_{d-1} \rangle\}$ 
نیز داریم
$\mathrm{tr} A=\sum_{i=0}^{d-1} \langle v_i\vert A\vert v_i\rangle$.

راهنمایی: اعضای پایه $\{\vert v_0 \rangle, \vert v_1 \rangle, \dots,\vert v_{d-1} \rangle\}$ را بر حسب پایه محاسباتی
$\{\vert 0 \rangle, \vert 1 \rangle, \dots,\vert {d-1} \rangle\}$ 
بسط دهید و از خاصیت متعامد یکه بودن استفاده کنید. روش دیگر این که می‌توانید از تساوی
$\sum_i \vert{v_i}\rangle \langle{v_i}\vert =I$
استفاده کنید.


2. نشان دهید برای هر دو ماتریس
 $A, B$
 داریم
$tr(AB)=tr(BA)$


3. نشان دهید
 $tr(A\otimes B)= tr(A) tr(B)$

## آماده‌سازی‌ها

In [166]:
import numpy as np

In [167]:
# you can create a random matrix/vector using this function
def complex_rand(*args):
    return np.random.rand(*args) * np.exp(1j * 2 * np.pi * np.random.rand(*args))

In [168]:
def dagger(x : str):
    return np.mat(x).conj().T
# e.g. dagger(np.mat([1 + 1j,0,0]))

In [169]:
# only use in 2nd and 3rd parts
np.trace?

In [170]:
# only for 3rd part
def tensor_product(a, b):
    return np.kron(a, b)

In [171]:
np.matmul?

In [172]:
np.dot?

In [173]:
np.linalg.norm?

## جوابِ سؤال به شکلِ کد

In [174]:
# part 1

def random_basis(d : int):
    res = []
    while len(res) < d:
        v = complex_rand(d, 1)
        for r in res:
            v -= complex(np.matmul(dagger(r), v)) * r
        if np.linalg.norm(v) == 0:
            continue
        v = v / np.linalg.norm(v)
        res.append(v)
    return res

d = 3

A = np.random.rand(d, d)
us = [] # standard basis
for i in range(d):
    u = np.array([[0]] * i + [[1]] + [[0]] * (d - i - 1))
    us.append(u)    
vs = random_basis(d)

tr_1 = sum([complex(np.matmul(dagger(u), np.matmul(A, u))) for u in us])
tr_2 = sum([complex(np.matmul(dagger(v), np.matmul(A, v))) for v in vs])

print("A = ", A)
print("vs = ", vs)

A =  [[0.0138207  0.98256123 0.90250655]
 [0.08977324 0.18821074 0.16648929]
 [0.84548975 0.79004111 0.39414387]]
vs =  [array([[-0.44383389+0.28302731j],
       [ 0.63636655-0.42350056j],
       [ 0.34667493-0.13567756j]]), array([[0.43685712-0.72396064j],
       [0.26844166-0.43933643j],
       [0.07371064-0.12052454j]]), array([[-0.08318307+0.03200698j],
       [ 0.38723955-0.02555366j],
       [-0.91226252-0.09605085j]])]


In [175]:
print(tr_1 - tr_2)

(-1.1102230246251565e-16+5.898059818321144e-17j)


In [176]:
# part 2
d = 3 # check for 3*3 matrix
A = np.random.rand(d, d)
B = np.random.rand(d, d)
print("A = ", A)
print("B = ", B)

A =  [[0.25761997 0.8199799  0.72153633]
 [0.61470549 0.89821421 0.22577435]
 [0.64164713 0.40129499 0.94694   ]]
B =  [[0.88181578 0.84254705 0.87450675]
 [0.69626815 0.22569976 0.39253732]
 [0.09894231 0.90585236 0.13269262]]


In [177]:
print(abs(np.trace(np.matmul(A, B)) - np.trace(np.matmul(B, A))) < 0.01)

True


In [178]:
# part 3
d_A = 3 
d_B = 4

A = np.random.rand(d_A, d_A)
B = np.random.rand(d_B, d_B)
print("A = ", A)
print("B = ", B)

A =  [[0.157383   0.88110995 0.48405122]
 [0.57883138 0.87553316 0.86691274]
 [0.27494286 0.70001743 0.87105294]]
B =  [[0.60271768 0.76241497 0.69919003 0.63489987]
 [0.85616135 0.80043641 0.42462866 0.10985439]
 [0.2697705  0.59441339 0.94820594 0.58744336]
 [0.88759019 0.10768886 0.5254831  0.50251493]]


In [179]:
print(np.trace(tensor_product(A, B)) - np.trace(A) * np.trace(B))

0.0


## جوابِ سؤال به شکلِ ریاضی

### جواب بخش ۱

ابتدا $|v_i\rangle$ را بسط می‌دهیم

$$ |v_i\rangle = \sum_j \alpha_{ij} |j\rangle $$

این‌که $v$ها یک پایهٔ متعامدیکه هستند نتیجه می‌دهد می‌توان $ \vert i \rangle $ را برحسبِ آن‌ها بست داد.

$$ \vert i \rangle = \sum_j \langle v_j \vert i \rangle \vert v_j \rangle = \sum_j \bar \alpha_{ji} \vert v_j \rangle $$

حالا باز چون پایهٔ متعامدیکه است، ضربِ داخلیِ دوبردار با ضربِ این ضرایب به دست می‌آید، یعنی برای دو بردار به شکلِ زیر

$$ \langle j \vert i \rangle = \sum_k \bar{\bar \alpha}_{kj} \bar \alpha_{ki} = \sum_k \alpha_{kj} \bar \alpha_{ki} $$

و از طرفی این دو بردار خودشان یک پایهٔ اند و ضربشان با توجه به عمود بودن و یکه بودن، به شکلِ زیر است.
$$
\langle i \vert j \rangle = \begin{cases} 0 & i \ne j\\ 1 & i = j\end{cases}
$$

حالا اگر برگردیم به مسئله و تریسِ خواسته‌شده را بنویسیم

$$ \sum_{i=0}^{d-1} \langle v_i\vert A\vert v_i\rangle = \sum_i \sum_{j, k} (\bar\alpha_{ij}\alpha_{ik}) \langle j \vert A \vert k \rangle $$

اگر ترتیبِ جمع‌ها را عوض کنیم و از رابطهٔ اثبات‌شدهٔ فوق استفاده کنیم، می‌توانیم به شکلِ زیر ساده‌سازی را انجام دهیم

$$ \sum_{i=0}^{d-1} \langle v_i\vert A\vert v_i\rangle = \sum_{j, k} \big(\begin{cases} 0 & j \ne k\\ 1 & j = k\end{cases}\big) \langle j \vert A \vert k \rangle = \sum_j \langle j \vert A \vert j \rangle = \mathrm{tr} (A)$$


### جواب بخش ۲

اول از تعریف ضرب ماتریسی استفاده می‌کنیم تا حاصل AB را به دست آوریم.
$$(AB)_{ij} = \sum_k A_{ik} B_{kj}$$
از طرفی می‌دانیم که تریس حاصل جمع درایه‌های قطری است.
$$\mathrm{tr} (AB) = \sum_i (AB)_{ii} = \sum_i \sum_k A_{ik} B_{ki} $$
حالا اگر دوتا جمع بالا را جابه‌جا کنیم می‌توانیم عبارت خواسته شده را نشان دهیم.
$$\mathrm{tr}(AB) = \sum_i \sum_k A_{ik} B_{ki} = \sum_k \sum_i B_{ki} A_{ik} = \sum_k (BA)_{kk} = \mathrm{tr}(BA)$$

### جواب بخش ۳

می‌دانیم که اگر یک پایه برای فضای $A$ به نامِ  $ \{\vert v_i \rangle\}$و یک پایه برای فضای $B$ به نامِ $ \{\vert u_i \rangle\}$ داشته‌باشیم

مجموعهٔ زیر پایه‌ای برای فضای ضربِ تانسوریِ این‌دو است.

$$ \{ \vert v_i \rangle \otimes \vert u_j \rangle \} $$

پس، می‌توان تریس را به این صورت محاسبه کرد

$$ \mathrm{tr}(A \otimes B) = \sum_{i, j} 
(\langle v_i \vert \otimes \langle u_j \vert)  (A \otimes B) (\vert v_i \rangle \otimes \vert u_j \rangle)  $$

که به این صورت ساده می‌شود.

$$ \mathrm{tr}(A \otimes B) = \sum_{i} 
\langle v_i \vert A \vert v_i \rangle \sum_{j} \langle u_j \vert B \vert u_j \rangle = \mathrm{tr}(A)\mathrm{tr}(B) $$