# سؤالِ ششم

 در این تمرین با شاهد‌های درهم‌تنیدگی آشنا می‌شویم.
ماتریس $M$ در فضای تانسوری را به صورت زیر تعریف کنید
$$M= \vert0\rangle \langle0\vert \otimes \vert0\rangle \langle0\vert + \vert0\rangle \langle1\vert\otimes \vert1\rangle \langle0\vert + \vert1\rangle \langle0\vert\otimes \vert0\rangle \langle1\vert + \vert1\rangle \langle1\vert\otimes \vert1\rangle \langle1\vert$$

  
1. نشان دهید برای هر دو بردار ۲-بعدی $\vert v\rangle, \vert w\rangle $،  داریم
$\langle v\vert\otimes \langle w\vert M \vert v\rangle \otimes \vert w\rangle \geq 0$

2. نشان دهید $M$ یک مقدار ویژه منفی دارد، و نتیجه بگیرید بردار $\vert\psi\rangle$ 
در فضای تانسوری وجود دارد به طوری که
$\langle \psi \vert M\vert \psi\rangle<0$


عملگر $M$ با دو خاصیت فوق، یک «شاهد درهم‌تنیدگی یا Entanglement witness» نامیده می‌شود. در واقع طبق این تمرین فقط بعضی از بردار‌های فضای تانسوری را می‌توان به فرم $\vert v\rangle \otimes \vert w\rangle$
نوشت که به آنها بردارهای ضربی گویند. برداری که ضربی نباشد را بردار درهم‌تنیده گویند. ماتریس $M$
بالا را یک شاهد درهم‌تنیدگی است چون  $\langle \phi \vert M\vert \phi\rangle$
برای همه برداری‌های ضربی مثبت است، ولی برای بعضی از بردار‌های درهم‌تنیده، منفی است.



## آماده‌سازی‌ها

In [2]:
import numpy as np

In [3]:
# you can create a random matrix/vector using this function
def complex_rand(*args):
    return np.random.rand(*args) * np.exp(1j * 2 * np.pi * np.random.rand(*args))

In [4]:
def dagger(x : str):
    return np.mat(x).conj().T
# e.g. dagger(np.mat([1 + 1j,0,0]))

In [5]:
def tensor_product(a, b):
    return np.kron(a, b)

In [6]:
# part 2
# Hint: use the determinant of matrix M
# the determinant of a matrix is the product of all eigenvalues
np.linalg.det?

## جوابِ سؤال به شکلِ کد

In [7]:
# creat M
ket0 = np.reshape(np.array([1, 0]),(2,1))
ket1 = np.reshape(np.array([0, 1]),(2,1))

M = tensor_product(np.matmul(ket0,dagger(ket0)),np.matmul(ket0,dagger(ket0))) + \
    tensor_product(np.matmul(ket0,dagger(ket1)),np.matmul(ket1,dagger(ket0))) + \
    tensor_product(np.matmul(ket1,dagger(ket0)),np.matmul(ket0,dagger(ket1))) + \
    tensor_product(np.matmul(ket1,dagger(ket1)),np.matmul(ket1,dagger(ket1)))
print(M)

[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [8]:
# part 1

# two random states
v = complex_rand(2,1)
w = complex_rand(2,1)

print((np.matmul(tensor_product(dagger(v),dagger(w)), np.matmul(M, tensor_product(v,w))) > 0).all())

True


In [9]:
# part 2

print((np.linalg.det(M) < 0).all())

True


## جوابِ سؤال به شکلِ ریاضی

### جواب بخش ۱

\begin{align*}
\langle v\vert\otimes \langle w\vert M \vert v\rangle \otimes \vert w\rangle = &  
 |\langle v\vert 0 \rangle|^2 |\langle w\vert 0\rangle|^2+ \langle v\vert 0\rangle \langle 1\vert v \rangle \langle w\vert 1\rangle \langle 0\vert w \rangle + \langle v\vert 1\rangle \langle 0\vert v \rangle \langle w\vert 0\rangle \langle 1\vert w \rangle+ |\langle v\vert 1 \rangle|^2 |\langle w\vert 1\rangle|^2  \\ = &
 \Big| \langle v\vert 0 \rangle \langle 0\vert w \rangle + \langle v\vert 1 \rangle \langle 1\vert w \rangle \Big|^2 \geq 0 
\end{align*} 

### جواب بخش ۲

میدانیم دترمینان یک ماتریس برابر با حاصل ضرب همه مقادیر ویژه آن است. پس اگر یک مقدار ویژه منفی داشته باشیم دترمینان باید منفی باشد. نمایش ماتریسی 
$M$
 در پایه 
 $\{00,01,10,11\}$
 برابر است با
 $$\begin{bmatrix}
 1 & 0 & 0 & 0 \\ 
 0 & 0 & 1 & 0 \\ 
 0 & 1 & 0 & 0 \\ 
 0 & 0 & 0 & 1
 \end{bmatrix}.$$
 لذا دترمینان
 $M$
 برابر با
 $-1$ 
 است. پس حداقل یک بردار ویژه نامنفی دارد.
